export const waitingMessages = [
  "Scanning for the one person who thinks beating you is a love language.",
  "Charging your heart energy for a suspiciously romantic showdown.",
  "Someone out there is stretching their fingers for a dramatic defeat.",
  "Polishing the next match until it sparkles just enough.",
  "Listening for a heartbeat that sounds competitive.",
  "Sketching tiny hearts around your future opponent's name.",
  "Teaching the universe how to flirt faster.",
  "Finding someone bold enough to meet your next move.",
  "Searching for a rival with excellent eye contact energy.",
  "Pairing your charm with someone equally dangerous.",
  "Warming up the board for a soft little war.",
  "Checking nearby hearts for courage, wit, and decent timing.",
  "Looking for a match with suspiciously good instincts.",
  "Someone is about to become your favorite problem.",
  "Aligning blush tones and battle plans.",
  "Tuning the room to premium romantic tension.",
  "Negotiating with fate for a very playable connection.",
  "Dusting glitter off a nearly perfect opponent.",
  "Letting the doodles know company is coming.",
  "Testing the chemistry meter and pretending not to grin.",
  "Hunting for someone who can lose beautifully or win kindly.",
  "Shuffling your destiny into the next available heartbeat.",
  "Matching confidence levels with a hint of chaos.",
  "Whispering your stats to the matchmaking gods.",
  "Building suspense one floating heart at a time.",
  "Locating a worthy distraction for your attention span.",
  "Searching for the exact right amount of trouble.",
  "Waiting for somebody with game and a pulse.",
  "Sweeping the board and dimming the lights a little.",
  "Inviting serendipity to stop being dramatic and hurry up.",
  "Someone is two clicks away from losing on purpose.",
  "Training the red doodles to celebrate your entrance.",
  "Checking if destiny prefers bold moves or cute ones today.",
  "Stirring flirtation into the signal feed.",
  "Tapping the glass to wake up your next opponent.",
  "Making room for a story that starts with a tiny board.",
  "Gathering blush, timing, and one excellent rival.",
  "A charming collision is loading.",
  "Measuring spark levels in real time.",
  "Looking for a match who can handle a playful plot twist.",
  "Someone nearby is about to regret underestimating you.",
  "Adding extra softness to your future win screen.",
  "Stretching the suspense so it lands just right.",
  "Checking the room for chemistry and competitive spirit.",
  "Trying not to announce that you look very beatable in the best way.",
  "Loading a person who might become your favorite notification.",
  "Comparing laugh frequencies for ideal pairing.",
  "A very specific kind of chaos is on its way.",
  "Sweeping in a fresh batch of hopeful coincidence.",
  "Your next rival is probably fixing their hair.",
  "Searching for someone who can weaponize a cute answer.",
  "Matching your vibe with a romantic wildcard.",
  "A soft little duel is buffering.",
  "Looking for a co-star with decent reflexes and dangerous charm.",
  "Finding the person most likely to blush at the wrong moment.",
  "Letting the hearts orbit dramatically while we search.",
  "Pairing wit with timing and one suspicious smile.",
  "Locating a match with main-character energy.",
  "Searching for a heartbeat with good banter potential.",
  "Clearing a lane for your next emotional side quest.",
  "The universe is speed-dating your luck.",
  "Fetching someone who might quote this later.",
  "Lining up your next impossible-to-ignore moment.",
  "Counting down to a stranger becoming specific.",
  "Making your waiting screen flirt back a little.",
  "Listening for footsteps, tension, and a tiny pulse.",
  "Preparing your next meet-cute with unnecessary style.",
  "A rival with soft eyes and sharp tactics may be approaching.",
  "Running diagnostics on chemistry, courage, and timing.",
  "Searching every corner for a beautifully timed challenge.",
  "Somebody is about to be very brave for no reason.",
  "Practicing your mysterious aura while we look around.",
  "Casting a net made of blush and anticipation.",
  "Scanning for the person who will absolutely make this interesting.",
  "Threading romance through the matchmaking engine.",
  "One lovely ambush coming right up.",
  "Checking who is available, attractive, and mildly competitive.",
  "Dusting off a new round of butterflies.",
  "Searching for a stranger with excellent almost-date energy.",
  "Someone nearby is about to unlock your attention.",
  "Arranging the doodles into a better omen.",
  "Calling in a match with brave thumbs.",
  "Stacking the deck with charm and coincidence.",
  "Looking for your next favorite distraction.",
  "Humming softly at the edge of a meet-cute.",
  "Searching for a connection that starts with a challenge.",
  "The board is ready. Your rival is late on purpose.",
  "Hoping your next opponent has range and restraint.",
  "Scanning for someone who knows how to lose with sparkle.",
  "Adjusting the lighting for your next tiny obsession.",
  "Finding a worthy heart to trouble.",
  "Crosschecking names against butterflies.",
  "The sketch lines are circling somebody already.",
  "Looking for the right amount of danger in a smile.",
  "Turning suspense into foreplay for conversation.",
  "Pulling a match out of the soft pink static.",
  "Searching for someone who can keep up with your little storm.",
  "Queuing up a romantic plot twist with better timing.",
  "Your next move is loading before your next person does.",
  "All signs point to trouble, charm, and one new match."
];

export const questionPrompts = [
  { id: "flirty-01", category: "flirty", text: "What tiny thing would instantly make this feel more like a date?" },
  { id: "flirty-02", category: "flirty", text: "If we met in person tonight, what would you secretly hope I noticed first?" },
  { id: "flirty-03", category: "flirty", text: "What's the most dangerous kind of smile someone can give you?" },
  { id: "flirty-04", category: "flirty", text: "Would you rather win the game or win my full attention for ten minutes?" },
  { id: "flirty-05", category: "flirty", text: "What's your favorite kind of accidental tension with someone new?" },
  { id: "flirty-06", category: "flirty", text: "What compliment works on you faster than it should?" },
  { id: "flirty-07", category: "flirty", text: "What's more attractive: confidence, humor, or dangerously good eye contact?" },
  { id: "flirty-08", category: "flirty", text: "What's one text from the right person that would ruin your focus today?" },
  { id: "flirty-09", category: "flirty", text: "What's your favorite excuse to stay talking to someone longer than planned?" },
  { id: "flirty-10", category: "flirty", text: "If I dared you to flirt badly on purpose, what line would you use?" },
  { id: "flirty-11", category: "flirty", text: "What kind of first touch always feels electric: hand, shoulder, or waist?" },
  { id: "flirty-12", category: "flirty", text: "What's the boldest thing someone could say that might actually work on you?" },
  { id: "flirty-13", category: "flirty", text: "Do you fall harder for mystery, warmth, or playful confidence?" },
  { id: "flirty-14", category: "flirty", text: "What's more dangerous on a date: chemistry, timing, or both?" },
  { id: "flirty-15", category: "flirty", text: "If a date goes perfectly, what's the moment you replay later?" },
  { id: "flirty-16", category: "flirty", text: "What's your version of an unmistakably flirty look?" },
  { id: "flirty-17", category: "flirty", text: "What would make you say, 'Okay, this person is trouble' in the best way?" },
  { id: "flirty-18", category: "flirty", text: "What's the quickest way to make you blush and pretend you're fine?" },
  { id: "flirty-19", category: "flirty", text: "What's more dangerous on you: teasing, eye contact, or a low voice?" },
  { id: "flirty-20", category: "flirty", text: "What innocent move can still feel wildly attractive to you?" },
  { id: "flirty-21", category: "flirty", text: "What's the most distracting thing someone you like can do?" },
  { id: "flirty-22", category: "flirty", text: "Would you rather get a bold compliment or a bold invitation?" },
  { id: "flirty-23", category: "flirty", text: "What's a line someone could say that would absolutely stay in your head?" },
  { id: "flirty-24", category: "flirty", text: "What's the kind of tension that makes you instantly want another round?" },
  { id: "funny-01", category: "funny", text: "What's the least attractive way someone could try to impress you?" },
  { id: "funny-02", category: "funny", text: "If your flirting style were a kitchen appliance, what would it be?" },
  { id: "funny-03", category: "funny", text: "What harmless habit of yours could absolutely end a situationship?" },
  { id: "funny-04", category: "funny", text: "What's your most dramatic overreaction to having a crush?" },
  { id: "funny-05", category: "funny", text: "If we got stuck in a terrible date movie, what role would you play?" },
  { id: "funny-06", category: "funny", text: "What's a ridiculous green flag that still matters to you?" },
  { id: "funny-07", category: "funny", text: "What would your friends say is your most suspicious dating talent?" },
  { id: "funny-08", category: "funny", text: "What's the weirdest thing that could make a date unforgettable?" },
  { id: "funny-09", category: "funny", text: "If chemistry had a terrible sound effect, what would it be?" },
  { id: "funny-10", category: "funny", text: "What's your funniest self-sabotage move when you actually like someone?" },
  { id: "funny-11", category: "funny", text: "Which is scarier: a first kiss or asking where to eat?" },
  { id: "funny-12", category: "funny", text: "What innocent text can still send you into a full spiral?" },
  { id: "funny-13", category: "funny", text: "What's the pettiest reason you could reject a date?" },
  { id: "funny-14", category: "funny", text: "If butterflies were honest, what rude thing would they yell before a date?" },
  { id: "funny-15", category: "funny", text: "What's your biggest red flag when you're sleep-deprived?" },
  { id: "funny-16", category: "funny", text: "If attraction had a loading screen tip, what would it say?" },
  { id: "funny-17", category: "funny", text: "What's one chaotic thing you'd do just to make someone laugh?" },
  { id: "funny-18", category: "funny", text: "What's the dumbest thing that would still make you fold a little?" },
  { id: "funny-19", category: "funny", text: "What's your funniest fake-cool move when you like someone?" },
  { id: "funny-20", category: "funny", text: "What harmless thing would make you say, 'Okay wow, marry me' jokingly?" },
  { id: "funny-21", category: "funny", text: "If flirting had an emergency exit, what would make you use it?" },
  { id: "personality-01", category: "personality", text: "What kind of energy do you naturally bring into a room?" },
  { id: "personality-02", category: "personality", text: "What's something people misunderstand about you at first?" },
  { id: "personality-03", category: "personality", text: "What trait makes you trust someone faster?" },
  { id: "personality-04", category: "personality", text: "When do you feel most like yourself?" },
  { id: "personality-05", category: "personality", text: "What's a small ritual that instantly resets your mood?" },
  { id: "personality-06", category: "personality", text: "What do you protect the most: peace, freedom, or closeness?" },
  { id: "personality-07", category: "personality", text: "What kind of compliment actually stays with you?" },
  { id: "personality-08", category: "personality", text: "What's one thing you are quietly very proud of?" },
  { id: "personality-09", category: "personality", text: "What vibe are you trying to leave behind after someone meets you?" },
  { id: "personality-10", category: "personality", text: "What usually wins your attention first: kindness, wit, or confidence?" },
  { id: "personality-11", category: "personality", text: "What's one boundary that actually protects your softness?" },
  { id: "personality-12", category: "personality", text: "What kind of person makes you immediately feel safe?" },
  { id: "personality-13", category: "personality", text: "What's your most underrated quality in dating?" },
  { id: "personality-14", category: "personality", text: "What do you notice first about someone's character?" },
  { id: "personality-15", category: "personality", text: "When do you become unexpectedly brave?" },
  { id: "personality-16", category: "personality", text: "What's one thing you'd rather be felt for than praised for?" },
  { id: "personality-17", category: "personality", text: "Which version of you shows up when you really like someone?" },
  { id: "personality-18", category: "personality", text: "What's one trait of yours that gets more attractive the longer people know you?" },
  { id: "personality-19", category: "personality", text: "What part of you only shows up around someone you really trust?" },
  { id: "personality-20", category: "personality", text: "What's your best quality in romance that people don't guess right away?" },
  { id: "hypothetical-01", category: "hypothetical", text: "If we had to fake-date for a weekend, what's the first rule you'd invent?" },
  { id: "hypothetical-02", category: "hypothetical", text: "If you could pause time during one moment of a date, which moment would it be?" },
  { id: "hypothetical-03", category: "hypothetical", text: "If we were characters in a romance game, what bonus skill would you want?" },
  { id: "hypothetical-04", category: "hypothetical", text: "If your heart sent push notifications, what would yours say tonight?" },
  { id: "hypothetical-05", category: "hypothetical", text: "If you had to win someone over using only food, what would you choose?" },
  { id: "hypothetical-06", category: "hypothetical", text: "If we got one free plane ticket tomorrow, what kind of trip starts the story?" },
  { id: "hypothetical-07", category: "hypothetical", text: "If attraction had weather, what forecast describes you best?" },
  { id: "hypothetical-08", category: "hypothetical", text: "If you could read one safe thought after a first date, what would you want it to be?" },
  { id: "hypothetical-09", category: "hypothetical", text: "If your ideal relationship had a soundtrack, what kind of song opens it?" },
  { id: "hypothetical-10", category: "hypothetical", text: "If you had to describe chemistry without using the word chemistry, what would you say?" },
  { id: "hypothetical-11", category: "hypothetical", text: "If we were trapped in an elevator for one hour, what topic saves us?" },
  { id: "hypothetical-12", category: "hypothetical", text: "If your future partner had a signature move, what would you hope it is?" },
  { id: "hypothetical-13", category: "hypothetical", text: "If you could skip straight to one relationship milestone, which one feels exciting?" },
  { id: "hypothetical-14", category: "hypothetical", text: "If we had to communicate with only songs for a day, what vibe would you send first?" },
  { id: "hypothetical-15", category: "hypothetical", text: "If your dating life got a warning label, what would be printed on it?" },
  { id: "hypothetical-16", category: "hypothetical", text: "If we swapped lives for 24 hours, what would surprise me most about yours?" },
  { id: "hypothetical-17", category: "hypothetical", text: "If you could script the perfect accidental meeting, where would it happen?" },
  { id: "hypothetical-18", category: "hypothetical", text: "If we had one midnight hour together in a city, where are we going first?" },
  { id: "hypothetical-19", category: "hypothetical", text: "If you could hear one honest sentence after a great date, what would you want?" },
  { id: "hypothetical-20", category: "hypothetical", text: "If chemistry had a dare mode, what would unlock first?" },
  { id: "hypothetical-21", category: "hypothetical", text: "If we had to turn this game win into a real plan, what would it be?" },
  { id: "emotional-01", category: "light-emotional", text: "What's something gentle that instantly makes you feel seen?" },
  { id: "emotional-02", category: "light-emotional", text: "When do you feel the most cared for without anyone saying much?" },
  { id: "emotional-03", category: "light-emotional", text: "What's one thing that softens you faster than expected?" },
  { id: "emotional-04", category: "light-emotional", text: "What's a quiet sign that you're getting attached?" },
  { id: "emotional-05", category: "light-emotional", text: "What kind of honesty feels especially attractive to you?" },
  { id: "emotional-06", category: "light-emotional", text: "What's one thing you'd love someone to understand about your heart early?" },
  { id: "emotional-07", category: "light-emotional", text: "What helps you open up without feeling rushed?" },
  { id: "emotional-08", category: "light-emotional", text: "What's the difference between feeling noticed and feeling known to you?" },
  { id: "emotional-09", category: "light-emotional", text: "What's a small act that feels unexpectedly intimate?" },
  { id: "emotional-10", category: "light-emotional", text: "What makes a connection feel calm instead of confusing?" },
  { id: "emotional-11", category: "light-emotional", text: "What part of closeness takes you longest to trust?" },
  { id: "emotional-12", category: "light-emotional", text: "What does emotional safety look like in a simple moment?" },
  { id: "emotional-13", category: "light-emotional", text: "What tiny reassurance means more to you than people realize?" },
  { id: "emotional-14", category: "light-emotional", text: "What kind of consistency instantly earns points with you?" },
  { id: "emotional-15", category: "light-emotional", text: "What's something you hope love feels like, not just looks like?" },
  { id: "emotional-16", category: "light-emotional", text: "What's one soft truth about you that a good person should know?" },
  { id: "emotional-17", category: "light-emotional", text: "What's a quiet way someone could make you feel chosen?" },
  { id: "emotional-18", category: "light-emotional", text: "What's one tiny thing that melts your guard more than it should?" },
  { id: "emotional-19", category: "light-emotional", text: "What kind of attention feels intimate without trying too hard?" },
  { id: "future-01", category: "future/date-vibes", text: "What's your ideal first date if the vibe is already dangerously good?" },
  { id: "future-02", category: "future/date-vibes", text: "What kind of plan says, 'I actually like spending time with you'?" },
  { id: "future-03", category: "future/date-vibes", text: "What's a place you'd save for someone with real potential?" },
  { id: "future-04", category: "future/date-vibes", text: "Which date has better odds: coffee and wandering or dinner and eye contact?" },
  { id: "future-05", category: "future/date-vibes", text: "What's a future memory you'd love to accidentally create with someone?" },
  { id: "future-06", category: "future/date-vibes", text: "What's your perfect length for a first date that goes too well?" },
  { id: "future-07", category: "future/date-vibes", text: "What's a tiny tradition you'd love to build with someone?" },
  { id: "future-08", category: "future/date-vibes", text: "What kind of weekend would quietly convince you to like someone more?" },
  { id: "future-09", category: "future/date-vibes", text: "What's your favorite sign that a second date should absolutely happen?" },
  { id: "future-10", category: "future/date-vibes", text: "What vibe should a great first night together have: cozy, electric, or funny?" },
  { id: "future-11", category: "future/date-vibes", text: "What's the most romantic ordinary thing two people can do together?" },
  { id: "future-12", category: "future/date-vibes", text: "What kind of invitation feels impossible to resist?" },
  { id: "future-13", category: "future/date-vibes", text: "What would a genuinely memorable date smell, sound, or feel like?" },
  { id: "future-14", category: "future/date-vibes", text: "What kind of future plan makes you feel chosen instead of casual?" },
  { id: "future-15", category: "future/date-vibes", text: "If sparks stay strong, what would you want round three to be?" },
  { id: "future-16", category: "future/date-vibes", text: "What's one date idea that feels cute, confident, and very you?" },
  { id: "future-17", category: "future/date-vibes", text: "What's the kind of invite that would make you say yes too fast?" },
  { id: "future-18", category: "future/date-vibes", text: "What's a second-date move that feels bold in a good way?" },
  { id: "future-19", category: "future/date-vibes", text: "If the vibe is unreal, where should a date end?" },
  { id: "future-20", category: "future/date-vibes", text: "What's an ordinary plan that becomes romantic with the right person?" },
  { id: "future-21", category: "future/date-vibes", text: "What future moment would make you think, 'Okay, this is becoming something'?" }
];

export const buttonMessages = [
  "Play the cute card",
  "Make it interesting",
  "Touch fate gently",
  "Stir the tension",
  "Open the soft chaos",
  "Tempt destiny",
  "Send the spark",
  "Try your luck, heartbreaker",
  "Press here for butterflies",
  "Challenge someone pretty brave",
  "Let the board flirt first",
  "Call in a better story",
  "Wake the chemistry",
  "Risk a tiny obsession",
  "Give fate a nudge",
  "Unlock the next pulse",
  "Start the trouble softly",
  "Make the moment blush",
  "Deal the next heartbeat",
  "Send a secret match"
];

export const leaveMessages = [
  "Don't leave yet. Your next move could be everything.",
  "One more round might be the plot twist.",
  "Leaving now feels suspiciously dramatic.",
  "Stay. Somebody out there is warming up for you.",
  "You could quit, but the tension would go to waste.",
  "What if your best answer was one round away?",
  "Not to be intense, but fate literally just sat down.",
  "If you leave now, the hearts will gossip.",
  "The board thinks you still have one good surprise left.",
  "You haven't even used your dangerous charm yet.",
  "Another move and this could get interesting.",
  "Leaving early is legal, but deeply unromantic.",
  "Give it one more tiny disaster.",
  "Your comeback story is still loading.",
  "Stay long enough to make it memorable.",
  "You look like someone who wins late.",
  "There is unfinished tension in the air.",
  "A soft exit is allowed. A perfect moment is still possible.",
  "One more game for science and chemistry.",
  "This feels like the part where you don't walk away."
];

export const outcomeMessages = {
  win: [
    "Clean win. Now make it interesting.",
    "That was dangerously smooth.",
    "You won the board. Earn the conversation.",
    "Sharp moves, softer consequences.",
    "Victory looks romantic on you.",
    "You played well. Now ask something worth remembering.",
    "One win closer to unlocking something real.",
    "The board folded first."
  ],
  lose: [
    "You lost the round, not the tension.",
    "A graceful loss still counts as chemistry.",
    "You got outplayed. Time to answer like it matters.",
    "The board chose drama for you.",
    "Take the loss. Keep the mystery.",
    "You may have lost, but now the story opens.",
    "Defeat looks better with honesty.",
    "Losing with style is still a move."
  ],
  draw: [
    "Nobody won, which means the tension survives.",
    "Draw. Equal danger on both sides.",
    "No winner. Plenty of unfinished business.",
    "That board ended in a stare-down.",
    "A draw is just mutual teasing in grid form.",
    "Nobody blinked. That's a vibe.",
    "Stalemate, but not exactly closure.",
    "The game called it even. Chemistry probably won't."
  ]
};
